jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.0.0
        with:
          hostname: 'https://valve.hogwild.uk'
          repository_root: '/home/wildhog/valvesite'
          branch: main
          cpanel_token: '${{ secrets.CPANEL }}'
          cpanel_username: wildhog
      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"
